### ISSUE TITLE
RuntimeError: await wasn't used with future

### ISSUE THREAD

**Issue by kpodp0ra** [StartITBot/sinGateway#1]
```
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-33463' coro=<Shard.received_message() done, defined at /var/singateway/singateway/shard.py:273> exception=RuntimeError("await wasn't used with future")>
Traceback (most recent call last):
  File "/var/singateway/singateway/shard.py", line 322, in received_message
    return await self.ensure_closed(code=1000)
  File "/var/singateway/singateway/shard.py", line 245, in ensure_closed
    await self._poll_task
RuntimeError: await wasn't used with future
```

**Comment by DomeQdev** [comment]
imagine robić issues na własnym repie
